"""Export a pack to the open RL-environment ecosystems.

AgentSynth's edge isn't hosting environments — it's verifying them. So a pack should
flow *into* the standards everyone is converging on rather than compete with them:

- a portable reward (`scenario_reward`) any framework can wrap — the outcome score,
  decoupled from any one library
- an OpenEnv server module (correct by construction — it calls our own `to_openenv`)
- a Prime Intellect `verifiers` environment with `load_environment`, ready to push to
  the Environments Hub, whose reward is the same world-state check
- a framework-neutral manifest describing the pack

    agentsynth pack export packs/core_v2.yaml --format verifiers --out dist/core_v2
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Sequence, Tuple, Union

Action = Dict[str, Any]


def _as_action(step: Union[str, Dict[str, Any]]) -> Action:
    if isinstance(step, str):
        return {"tool_name": "sql_query", "arguments": {"query": step}}
    return step


def scenario_reward(
    scenario: Any,
    actions: Sequence[Union[str, Dict[str, Any]]],
    answer: str = "",
    seed: int = 7,
) -> float:
    """Outcome score in [0, 1] for running `actions` (then `answer`) on a scenario.

    This is the portable, verifiable reward: replay the agent's actions on the seeded
    world and report the fraction of end-state checks that hold. Wrap it in a verifiers
    `Rubric`, a TRL reward, or your own loop — the number means the same thing.
    """
    from .rl import AgentGym

    plan = [_as_action(a) for a in actions]
    gym = AgentGym.from_scenario(scenario, seed=seed)

    def policy(observation: str, g: Any) -> Action:
        i = g.step_count
        return plan[i] if i < len(plan) else {"answer": answer}

    try:
        episode = gym.rollout(policy)
    finally:
        gym.close()
    return float(episode.info.get("outcome", {}).get("score", 0.0))


def actions_from_messages(messages: Sequence[Dict[str, Any]]) -> Tuple[List[Action], str]:
    """Pull (tool actions, final answer) out of an OpenAI-style completion.

    This is the bridge verifiers needs: its rollout hands you assistant messages with
    `tool_calls`; we turn those into gym actions and take the last assistant text as
    the final answer.
    """
    from .adapters import action_from_openai_tool_call

    actions: List[Action] = []
    answer = ""
    for message in messages:
        if message.get("role") != "assistant":
            continue
        for call in message.get("tool_calls") or []:
            actions.append(action_from_openai_tool_call(call))
        if message.get("content"):
            answer = str(message["content"])
    return actions, answer


def reward_from_messages(scenario: Any, messages: Sequence[Dict[str, Any]], seed: int = 7) -> float:
    """Score an OpenAI-style completion against a scenario's world-state checks."""
    actions, answer = actions_from_messages(messages)
    return scenario_reward(scenario, actions, answer=answer, seed=seed)


def environment_manifest(scenarios: Sequence[Any], pack_id: str) -> Dict[str, Any]:
    """A framework-neutral card describing the pack as a verifiable environment."""
    tiers: Dict[str, int] = {}
    for scenario in scenarios:
        tier = str(scenario.metadata.get("tier", "unspecified"))
        tiers[tier] = tiers.get(tier, 0) + 1
    return {
        "id": pack_id,
        "kind": "agentsynth-pack",
        "n_scenarios": len(scenarios),
        "tiers": tiers,
        "reward": "outcome: fraction of end-state checkers that pass (verifiable, 0..1)",
        "scenarios": [
            {"id": s.id, "task": s.task, "tier": s.metadata.get("tier")} for s in scenarios
        ],
    }


def to_openenv_module(pack_filename: str, pack_id: str) -> str:
    """A self-contained OpenEnv server module for the pack (uses our bridge)."""
    return f'''"""OpenEnv environment for the {pack_id} pack (generated by AgentSynth).

Each scenario becomes an episode: tool calls execute for real and the terminal reward
is the world-state verdict. Needs `pip install "agentsynth-ai[rl]"` (Python 3.10+).

    from {pack_id}_openenv import make_environment
    env = make_environment("{pack_id}")        # first scenario by default
    obs = env.reset()
"""

from pathlib import Path

from agentsynth.rl import AgentGym, to_openenv
from agentsynth.scenarios import load_scenarios

PACK = Path(__file__).parent / "{pack_filename}"


def _scenarios():
    return {{scenario.id: scenario for scenario in load_scenarios(str(PACK))}}


def make_environment(scenario_id=None, seed=7):
    """Wrap one pack scenario as an OpenEnv environment."""
    scenarios = _scenarios()
    if scenario_id is None:
        scenario_id = next(iter(scenarios))
    gym = AgentGym.from_scenario(scenarios[scenario_id], seed=seed)
    return to_openenv(gym)
'''


def to_verifiers_module(pack_filename: str, pack_id: str) -> str:
    """A Prime Intellect `verifiers` environment with `load_environment`.

    The reward is AgentSynth's world-state check, so a model can't talk its way to a
    score. Install `verifiers` and `agentsynth-ai`, then push the folder to the
    Environments Hub.
    """
    return f'''"""`verifiers` environment for the {pack_id} pack (generated by AgentSynth).

The reward is the world-state check: the agent's tool calls are replayed on the seeded
world and scored on the end state, not the transcript. Install and run:

    pip install verifiers agentsynth-ai
    vf-eval {pack_id}

Push the folder to the Prime Intellect Environments Hub to share it.
"""

from pathlib import Path

import verifiers as vf
from datasets import Dataset

from agentsynth.pack_export import reward_from_messages
from agentsynth.scenarios import load_scenarios

PACK = Path(__file__).parent / "{pack_filename}"


def load_environment(**kwargs):
    scenarios = {{scenario.id: scenario for scenario in load_scenarios(str(PACK))}}
    rows = [
        {{
            "question": scenario.task,
            "answer": scenario.metadata.get("answer", ""),
            "info": {{"scenario_id": scenario.id}},
        }}
        for scenario in scenarios.values()
    ]
    dataset = Dataset.from_list(rows)

    def outcome_reward(completion, info, **_):
        # `completion` is the model's messages; score them on the scenario's world state.
        return reward_from_messages(scenarios[info["scenario_id"]], completion)

    rubric = vf.Rubric(funcs=[outcome_reward], weights=[1.0])
    return vf.ToolEnv(dataset=dataset, rubric=rubric, **kwargs)
'''


def _pyproject(pack_id: str, fmt: str) -> str:
    extra = "rl" if fmt == "openenv" else "verifiers, datasets"
    return (
        "[project]\n"
        f'name = "{pack_id}-{fmt}"\n'
        'version = "0.1.0"\n'
        f'description = "AgentSynth {pack_id} pack as a {fmt} environment"\n'
        'requires-python = ">=3.10"\n'
        f'dependencies = ["agentsynth-ai"]  # plus: {extra}\n'
    )


def _readme(pack_id: str, fmt: str, manifest: Dict[str, Any]) -> str:
    return (
        f"# {pack_id} ({fmt})\n\n"
        f"{manifest['n_scenarios']} outcome-checked scenarios exported from the AgentSynth "
        f"`{pack_id}` pack. The reward is verifiable: {manifest['reward']}.\n\n"
        f"Tiers: {manifest['tiers']}\n\n"
        "Generated by `agentsynth pack export`.\n"
    )


def export_pack(pack_path: str, fmt: str, out_dir: str) -> List[str]:
    """Write a Hub-ready environment folder for a pack. Returns the files written."""
    from .scenarios import load_scenarios

    if fmt not in ("verifiers", "openenv"):
        raise ValueError(f"unknown format {fmt!r}; expected 'verifiers' or 'openenv'")
    scenarios = load_scenarios(pack_path)
    pack_id = os.path.splitext(os.path.basename(pack_path))[0]
    pack_filename = os.path.basename(pack_path)
    os.makedirs(out_dir, exist_ok=True)

    with open(pack_path, encoding="utf-8") as fh:
        pack_text = fh.read()
    manifest = environment_manifest(scenarios, pack_id)

    if fmt == "openenv":
        module_name = f"{pack_id}_openenv.py"
        module_text = to_openenv_module(pack_filename, pack_id)
    else:
        module_name = f"{pack_id}_verifiers.py"
        module_text = to_verifiers_module(pack_filename, pack_id)

    written = {
        pack_filename: pack_text,
        module_name: module_text,
        "pyproject.toml": _pyproject(pack_id, fmt),
        "README.md": _readme(pack_id, fmt, manifest),
        "manifest.json": json.dumps(manifest, indent=2, ensure_ascii=False),
    }
    paths = []
    for name, text in written.items():
        path = os.path.join(out_dir, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        paths.append(path)
    return paths


__all__ = [
    "scenario_reward",
    "actions_from_messages",
    "reward_from_messages",
    "environment_manifest",
    "to_openenv_module",
    "to_verifiers_module",
    "export_pack",
]
